### PR TITLE
fix syntax error farchi.sh

### PR DESCRIPTION
**Pull request by Paulobox**
I got an Error when I tried to Install fresh on line 34:

$(use_nonus_keymap()) && loadkeys "${default_keymap}"
 syntax error near unexpected token ')'
 
Changed it to this and it Launched:
 
if use_nonus_keymap; then
    loadkeys "${default_keymap}"
fi

### CODE REVIEW

**Comment by deepbsd** [comment]
Hey Paulobox!  Thanks for your interest!   

First `&amp;&amp;`   these are SGML entities that represent a double ampersand.  They of themselves are not executable code.  So please be sure your interpreter is not trying to execute those instead of the actual double ampersand.

Tell me, when you launched the script, did you launch it with bash or zsh?  And was it the latest bash from the latest installer?  When I launch the script it's  `# bash farchi.sh`   That way  the "&&" becomes a logical and.  Otherwise I'm confused as to why there would be a syntax error, unless it was either an older bash or another shell.  Modern bash should support the "&&" logical and operator.  (I believe zsh currently respects the logical and operator too, but I don't use zsh very much.)  But obviously, the if then structure avoids the problem altogether, so good job!  Please feel free to use it on your own copy or fork!   I think I'll keep the double ampersand unless you can show me the problem with it?

Again, thanks for the interest!

**Comment by Paulobox** [comment]
I just launched it fom Arch iso on vmware. I did chmod +x and ./farchi.sh.

**Comment by deepbsd** [comment]
The default shell for the Arch ISO is zsh, not bash.  So I would try using bash and let me know what happens for you, okay?

I'm not exactly sure whether `# ./farchi.sh` and `/usr/bin/env bash`  are going to be different from `#bash farchi.sh`.  But there might be a different ENV setup.  I always launch using `#bash farch.sh`    Can you let me know whether you still get a syntax error by doing that?  Launching with `#bash farchi.sh` ?

Thanks again for the feedback!

**Comment by Paulobox** [comment]
Screenshot 2024-05-22 204641

archlinux-2024.05.01-x86_64.iso

**Comment by Paulobox** [comment]
Screenshot 2024-05-22 204815

**Comment by Paulobox** [comment]
change keymap if necessary

i replace red part  and the script launched.

**Comment by deepbsd** [comment]
Ah, now I see it.   It should be this:  `$(use_nonus_keymap) && loadkeys "${default_keymap}"`    I had an extra`()` in there which is superfluous.  Oops.   Thanks for the catch Paulobox!

**Pull request closed without merging**
